### ISSUE TITLE
fifo에서 AFULL_THRESHOLD는 잘 최적화를 해야된다고 하셨는데 FIFO_DEPTH 또한 최적의 값을 찾아 수정하는 것인가요?

### ISSUE THREAD

**Issue by bhkim003** [ECE4278/project2#1]
일단 default 값은 FIFO_DEPTH          = 16 인데
이것을 threshold처럼 최적의 값을 연구해서 수정하면 되는 건가요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습조교 박태원입니다.

넵 그렇습니다, 각각의 FIFO의 FIFO_DEPTH의 크기도 조절하면서 performance와 area 측면에서 적합하다고 생각하는 값으로 설정하시면 됩니다.

**Comment by bhkim003** [comment]
감사합니다 조교님!
