### ISSUE TITLE
Test Bench Performance 질문

### ISSUE THREAD

**Issue by Zoon17** [ECE4278/project2#10]
안녕하세요,

기본적으로 주어진 spec 대로 설계한 경우(MSHR이나 별도 추가 구조 없이)
14주차 Project2 Supplement 의 12-page에 나와있는 성능이
최적의 성능이라고 보고
해당 성능을 타겟으로 최적화하면 될까요?

성능을 매 cycle 단위로 관찰해서
delay되는 부분을 최적화하고 있는데 
기준점을 잡고 싶어서 질문 드립니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 

12쪽에 나와있는 Time은 최적이라고 말하기는 어렵습니다. 제가 스펙에 이상이 없는지 확인하기 위해 RTL로 작성하고 추가적인 최적화 없이 시뮬레이션한 결과이기 때문에 최적이라고 보기는 어렵습니다. (물론 FIFO Depth는 조절하기는 했습니다.) 따라서 해당 결과는 최적의 성능은 아닙니다.

그리고, 참고로 추가적인 테스트도 진행한다는 점도 생각해주시기 바랍니다.  (gen_repeat_cnt와 access_repeat_cnt 값을 조절해서 몇 개의 테스트를 더 돌릴 것입니다.)

**Comment by Zoon17** [comment]
답변 감사합니다~
