### ISSUE TITLE
cache controller에서 inct ar ch과 mc ar ch관련하여 질문드립니다.

### ISSUE THREAD

**Issue by gpfla108** [ECE4278/project2#11]
조교님 안녕하세요.

cache controller에서 mem_ar ch의 mem_arid_o, mem_araddr_o, mr_arlen_o, mem_arsize_o, mem_arburst_o, mem_arvalid_o 를 셋팅하는 과정에서 질문이 있어서 문의드립니다.

mem의 arid, arlen, arsize, arburst, arvalid의 경우 inct의 arid, arlen, arsize, arburst, arvalid의 값을 assign 하려고 하는데,, mem의 araddr은 miss_req_fifo에서 가져온 delay된 것인데, 나머지 arid, arlen, arsize, arburst, arvalid는 inct의 현재 input값을 사용하는 것이 맞는지 궁금합니다.

정확히 하기 위해서는 inct의 arid, ~~, arvalid 값 또한 miss_req_fifo에서 가져온 address 의 delay만큼 저장해놨다가 delay된 값을 assign 해주어야하는지 궁금합니다.

또한 mem의 arvalid가 어떠한 상황에서 on이 되어야하는지도 궁금합니다.

바쁘신 와중에 확인하여주셔서 감사드립니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

1. mem의 arid, arlen, arsize, arburst, arvalid의 경우 inct의 arid, arlen, arsize, arburst, arvalid의 값을 assign 하려고 하는데,, mem의 araddr은 miss_req_fifo에서 가져온 delay된 것인데, 나머지 arid, arlen, arsize, arburst, arvalid는 inct의 현재 input값을 사용하는 것이 맞는지 궁금합니다. -> 어차피 arid, arlen, arsize, arburst (arvalid는 제외)는 이번 과제에서 변경되지 않기 때문에 inct의 현재 input값으로 넣으셔도 되고 아니면 상수값으로 assign 해줘도 무방합니다. 

2. mem arvalid는 ar 채널은 miss request fifo의 read interface와 엮여있습니다. mem ar채널에 유효한 address를 넘겨줄 수 있을 때의 fifo 상태를 생각해보시면 알아낼 수 있습니다.
