### ISSUE TITLE
AXI SLAVE, SRAM 수정 가능 여부

### ISSUE THREAD

**Issue by HIDDEN-IU** [ECE4278/project2#12]
프로젝트 제한 사항에 CC_TOP의 입출력포트를 수정하지 말라는 내용이 있고, 나머지는 자유롭게 바꿔도 된다고 하셨는데,

그래도 당연히 AXI_SLAVE의 AR2R_DELAY를 수정하는 것은 안되겠죠?

혹시나 수정하는 사람이 있을 것 같기도 한데, 수정해도 채점 환경에선 무의미한 것인지 궁금합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

프로젝트 제한사항은 제출할 파일들에 대한 내용입니다.
AXI_SLAVE, SRAM 등은 RTL 폴더 내에 있는 것이 아닌 SIM 폴더에 있는 테스트를 할 때 쓰는 것들이고, 해당 모듈들은 제출하는 모듈이 아니기 때문에 수정할 수 없습니다.
