### ISSUE TITLE
VIVADO 툴 시뮬레이션, 서버 시뮬레이션에 대해 질문입니다.

### ISSUE THREAD

**Issue by jyk2498** [ECE4278/project2#13]
안녕하십니까 조교님. 이번 기말 프로젝트와 관련하여 몇 가지 질문이 있어 질문 드립니다.

1. 다음은 VIVADO 에서의 시뮬레이션 결과입니다.
![881](https://user-images.githubusercontent.com/59245927/206836246-2564a6e0-cf57-4911-a6aa-fed94c504f9d.PNG)

![90_800](https://user-images.githubusercontent.com/59245927/206836251-7b77bef8-29bd-4d00-95be-623cb11977cf.PNG)
위 사진에서 보이듯이 파라미터를 80/800 으로 설정했음에도 881 번째 request 가 나오고 있음을 알 수 있는데, 왜 이런지 모르겠습니다. waveform 을 통해서 확인해 본 바로는 10,000,000,000 ns 까지 시뮬레이션이 진행되는데, 실제로 signal 들은 약 250,4500,000ns 까지만 변화를 하고 나머지는 clk 만 튀고 있는 상황이 관찰됩니다. 혹시 왜 그런지 알 수 있겠습니까?

2. 다음은 동일한 코드를 서버에서 돌린 결과입니다.
![mobexterm](https://user-images.githubusercontent.com/59245927/206836396-92c15d84-a3da-4d12-9152-c7d8c08b868a.PNG)
서버에서 돌린 경우에는 vivado 에서와 달리 시뮬레이션 결과가 다릅니다. 여러 번 돌려 보았음에도 서버와 vivado 에서 시뮬레이션 되는 상황이 동일합니다. 왜 이런지 알 수 있을까요?

3. 서버에서 verdi 를 켜려고 시도하는 경우 다음과 같은 오류가 뜹니다.
![verdi](https://user-images.githubusercontent.com/59245927/206836463-9cf1c688-9f8a-4a07-bb02-f0aa9db243b0.PNG)
혹시 이 오류를 해결할 방법이 있을까요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 
문제를 확인하기 위해 몇가지 정보가 더 필요합니다.

1.2. Vivado와 Synopsys 결과가 왜 다른지는 확인해봐야 알 수 있겠는데, 일단 last 신호가 잘못 들어가는 것 같습니다. 그 부분에서 먼저 검토를 해보시기 바랍니다. 그리고 Vivado에서 시뮬레이션 돌렸을 때, 서버에서 멈춘 구간 근처에서의 결과를 캡쳐해서 보여주세요. (644~645 request 부분)

3. MobaXterm에서 실행하고 있는 상황인가요? 아니면 다른 터미널을 사용 중이신가요?

**Comment by jyk2498** [comment]
![fddd](https://user-images.githubusercontent.com/59245927/206837651-45c52a99-7fa4-4f13-a7c7-6fe760e44069.PNG)

![VIVADO](https://user-images.githubusercontent.com/59245927/206837656-1a352ced-83bb-481a-b529-00cf465d3a22.PNG)

Mobexterm 을 통해 SAL 서버로 들어간 뒤에 사용하는 중입니다 (학부연구생이라 사용 가능합니다)

**Comment by pdtowctor** [comment]
제 생각에는 중간에 실수로 테스트벤치 코드를 건드신 것 같은데 (정답을 보니 그런 생각이 듭니다.) project2 전체를 다시 git clone해서 각각의 방법에서 다시 돌려보시기 바랍니다.

그리고 mobaXterm 로그인하실때 아래와 같이 X11-forwarding과 Display가 체크표시인지 확인해서 알려주시기 바랍니다. 

![image](https://user-images.githubusercontent.com/61111662/206838154-80952bc8-54bb-4205-b318-6451e4175c7c.png)

**Comment by jyk2498** [comment]
넵 해보겠습니다 감사합니다
