### ISSUE TITLE
Wiring 질문입니다.

### ISSUE THREAD

**Issue by dongwhee-kim** [ECE4278/project2#14]
안녕하세요, 조교님.
Tag comparator에서 wiring 질문입니다.

과제 그림에서 hit==1이면 hit_flag_fifo_wren이 켜지고, miss=1이어도 hit_flag_fifo_wren이 켜지는데 이러면 wiring에서 하나의 port에 2개의 wire가 연결되는데, TOP에서 이렇게 되면 문제가 발생하지 않나요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

hit 또는 miss가 1인 경우에 hit_flag_fifo_wren이 1로 띄우는 것을 TOP에서 표현하면 됩니다.
