### ISSUE TITLE
SRAM 관련 문의 드립니다.

### ISSUE THREAD

**Issue by parkseungah** [ECE4278/project2#15]
안녕하세요. SRAM data 관련 문의드립니다.
이번 프로젝트에서 HIT 상태일 때는 SRAM에 있던 데이터를 가져와야 하는 것으로 이해했는데, VIVADO 상에서 SRAM에 저장되어있던 데이터의 내용이 기존 데이터와 일치하는 지 확인하고 싶습니다.

![sram](https://user-images.githubusercontent.com/55955514/206917638-c186a1da-5124-4f60-8696-e4a0d0d21517.png)

VIVADO 상에서는 SRAM_DUAL_PORT_ARRAY 데이터가  XX...가 아니라면 512b 중 64b만이 0이 아닌 bit로 구성되었으며, 나머지 448b의 경우 모두 0으로 이루어진 것을 확인했습니다. 
예. SRAM 510번째 array 값 = c666b48cd03098a/00..0000(나머지 488b는 모두 0으로 구성)

사진과 같이 SRAM에서 일부 64b만 유의미한 값을 갖고 나머지는 488b 모두 0으로 구성되어 있는데, HIT일 때 error가 발생해서 이렇게 문의드리게 되었습니다.
우선 SRAM의 데이터 형식이 맞는지, 아니라면 혹시 해결할 방법이 있는지 알려주시면 감사드리겠습니다.

감사합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 

SRAM의 형식은 맞습니다. 현재 Index가 9bit이고, 2^9=512의 cache line이 SRAM에 있으며, 각 cache line의 크기는 64B(=512bit)이므로 해당 형식은 맞습니다.

SRAM 값이 이상한 이유는 SRAM에 값을 잘못 채워넣었기 때문입니다. SRAM을 채우는 역할을 하는 것은 Data Fill Unit이기 때문에, 해당 모듈에서 time diagram 등을 통해서 디버깅 해보시면 되겠습니다.

**Comment by parkseungah** [comment]
넵, 이해했습니다!

감사합니다.
