### ISSUE TITLE
net interconnect area = undefined 문의 드립니다.

### ISSUE THREAD

**Issue by bon9bong** [ECE4278/project2#16]
안녕하십니까, 2022712596 강석봉입니다. 과제에 대해 몇 가지 질문드립니다.

1. 합성 시 net interconnet area = undefined로 나오는데,
제가 설정을 잘 못한것인지 아니면 채점이 total cell area 기준으로 하는지 문의드립니다.
2. 연속된 동일 주소의 miss시,
tag match시 sram에 miss데이터가 수신되지 않았다면 
계속 동일 주소로 메모리에 리퀘스트를 보내는 것이 올바른 작동인지 여쭙니다.

늦은 질문 읽어주셔 감사드립니다.
강석봉 드림.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

1. 현재 합성시 zero wire load model을 사용하기 때문에 나오는 결과입니다.
2. 제가 질문을 정확히 이해 못했는데, 연속된 동일 주소의 request를 보내는 상황에서 tag comparator쪽에서 tag를 비교하기 위해 데이터를 가져왔을 때, SRAM에 miss된 데이터가 아직 안 온 경우에는 tag쪽에서 어차피 invalid인 상태일 겁니다. (정확히 구현했다면) 따라서 이 경우 miss pulse 신호가 나올 것이고, 동일 주소로 메모리에 request를 보낼 것입니다.

**Comment by bon9bong** [comment]
빠른 답변 감사드립니다!
2번도 말씀하신 내용 문의드린 것으로 해결되었습니다.

**Comment by pdtowctor** [comment]
그리고 답변 하나 깜빡했는데 채점은 Total cell area 기준으로 합니다.

**Comment by bon9bong** [comment]
확인하였습니다. 감사합니다.
