### ISSUE TITLE
합성 결과 관련하여 질문 드립니다.

### ISSUE THREAD

**Issue by GyubinSeong** [ECE4278/project2#17]
안녕하세요 조교님.
합성 결과 관련하여 질문 드립니다.

합성시에 warning이 몇가지 떴는데 synthesis completed 문구가 떴으면 문제 없는건가요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

일단 check_design.rpt을 확인해서 warning으로 뜬 부분에서 문제가 있는지 확인하셔야 합니다.
그 다음 hierarchy.rpt에서 top 모듈에서 인스턴스한 모듈들이 다 존재하는지 확인하시고, area.rpt에서도 마찬가지로 확인해주시면 큰 문제 없을겁니다.
