### ISSUE TITLE
현재 mobaXterm 접속이 안되는 것 같습니다.

### ISSUE THREAD

**Issue by bhkim003** [ECE4278/project2#2]
안 바쁘실 때 한번 확인해 주실 수 있으신가요?
김병현 올림

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

일단 파악한 바로는, 간헐적으로 학교망 밖에서는 접속이 잘 안 되는 상황인 것 같습니다.
저희가 사용하는 서버는 학과 공용 서버이므로, 해당 관리자분에게 문의해보겠습니다.

**Comment by bhkim003** [comment]
감사합니다!

**Comment by HIDDEN-IU** [comment]
혹시 명륜 캠퍼스에서도 서버 접속이 가능할까요?

**Comment by pdtowctor** [comment]
> 혹시 명륜 캠퍼스에서도 서버 접속이 가능할까요?

제가 알기로는 가능합니다.
