### ISSUE TITLE
mobaexterm 접속관련

### ISSUE THREAD

**Issue by rangfuu** [ECE4278/project2#4]
학교망에서도 접속이 잘 안되는 것같은데, 
제 환경설정 문제인지, 현재 서버문제인지 알 수 있을까요?
감사합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

학과서버 관리자에게 문의해본 결과, 현재 학교 측에서 소정의 사유로 포트를 차단해서 접속이 안 된다고 합니다. 
이 부분을 해결하는 과정 중에 있고, 다시 접속이 될 때 공지로 알려드리도록 하겠습니다.

**Comment by rangfuu** [comment]
넵 감사합니다
