### ISSUE TITLE
CC_DATA_FILL_UNIT의 포트중에 mem_rready_i에 대해서 질문 있습니다.

### ISSUE THREAD

**Issue by whdcks877** [ECE4278/project2#5]
CC_DATA_FILL_UNIT의 포트중에 메모리와 통신하는 axi인터페이스가 있는데 여기서 mem_rvalid_i와 mem_rready_i가 모두 입력 포트로 선언이 되어있습니다. 그런데 구현을 해보니 핸드셰이크를 위해서는 mem_rready_i 포트가 출력으로 나가야 할 것 같아서 그렇습니다만, 혹시 해당 포트는 입력으로 있는게 맞는지 아니면 단순 오타인지 여쭈어봅니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

비직관적이긴한데 일단 mem_rready는 data fill unit 입장에서는 입력 신호로 받는 것이 맞습니다. 

큰 그림을 보면 현재 mem R ch에 묶인 모듈은 data fill unit과 data reorder unit입니다.
mem R ch로 오는 data는 결국 Inct R ch로도 보내야하고, mem R ch에서 필요한 rready 신호는 Inct R ch의 rready 신호로부터 와야 하기 때문에, mem R ch과 Inct R ch에 같이 연결된 data reorder unit에서 Inct R ch의 rready 신호를 mem R ch로 보내는 역할을 해야합니다. (즉, mem R ch의 rready신호를 보내주는 담당을 하는 것은 data reorder unit 입니다.)

한편, data fill unit 입장에서는 mem R ch로 부터 오는 데이터를 받아서 SRAM에 데이터를 채워줘야 하는데, rvalid의 신호만으로 데이터를 채워주는 경우, mem R ch의 rready 신호가 아직 0인 경우에 오동작 할 수 있습니다. 즉, mem R ch로부터 오는 데이터는 rready와 rvalid가 handshake할 때에만 가져오는 것이 맞으므로, mem R ch의 rready 신호가 필요하며, 이 때 rready 신호는 mem R ch에서 오는 입력 포트를 통해 가져오면 됩니다.

다른 방법으로는 CC_TOP 모듈에서 mem r ch의 rready와 rvalid의 신호를 엮어서 handshake하는 신호를 추가로 생성하고 이를 data fill unit에 넣어주는 방법도 있습니다. rready신호와 rvalid신호를 입력으로 받는 대신에 하나의 handshake를 입력 신호로 받아서 data fill unit을 작성하셔도 됩니다.

정리하자면,
1. Data fill unit 입장에서는 handshake을 위해 mem rready 신호가 필요하고, 이를 입력으로 받아야 합니다.
2. mem rready 신호를 정해주는 역할을 하는 것은 data reorder unit입니다.

**Comment by whdcks877** [comment]
그렇군요! 감사합니다!
