### ISSUE TITLE
hit data fifo 관련 질문입니다

### ISSUE THREAD

**Issue by meenooksun** [ECE4278/project2#6]
hit data fifo에서 sram에서 data를 읽어올때 offset(6b)/ data(512b)라고 표현되어있는데 그렇다면 총 518b의 data가 fifo의 width가 되는 것인가요?

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

넵 그렇습니다. 518b의 data가 hit data fifo의 width라고 생각하면 됩니다.

물론 최적화를 하여 더 줄이는 방법이 있기는 합니다. (면적을 줄이는데 도움이 될 수 있습니다)
