### ISSUE TITLE
testbench result 질문있습니다.

### ISSUE THREAD

**Issue by bhkim003** [ECE4278/project2#7]
현재 CC_TOP_TB 내의 gen_repeat_cnt 값과 access_repeat_cnt 값을 임의로 변경해도 Pass the test! 문구는 잘
뜨면서 잘 돌아가는 것 같습니다.

 1. gen_repeat_cnt 값을 0으로 두고 (gen_repeat_cnt == 강의에서 miss 개수와 비슷하다고 하셨던 것) 그리고 
access_repeat_cnt 값을 0 초과 값 (5000) 을 주면  Pass the test! 문구는 뜨는데

![image](https://user-images.githubusercontent.com/62134040/204746805-74295b6d-b0c6-481a-bf53-649ad7e807e0.png)

위 사진처럼 request 에 대한 언급은 없고 test start ============ 와 Pass the test! 만 있습니다.

질문: 이번 텀프에서 gen_repeat_cnt == 0, access_repeat_cnt >0  인 경우 위 사진처럼 결과가 나와도 되는 것인가요?

 2. gen_repeat_cnt 대비 access_repeat_cnt를 증가 시키면 제 설계 기준으로 확실히 Time 이 감소하는 경향성을 눈에 띄게 
감소하는 것은 보이지만 교안에서 보여주신 gen_repeat_cnt == 500, access_repeat_cnt == 4500 의 경우는 교안에서는 
13억ps 정도이지만 제 설계로는 23억 ps가 나옵니다. 
 (gen_repeat_cnt == 5000, access_repeat_cnt == 0 의 경우는 교안과 비슷한 시간이 나옵니다.)

질문: 10억ps 정도의 차이는 무작위적인 차이 라기보다 hit data 쪽의 설계를 개선해야 할 유의미한 시간 차이인가요?

 김병현 올림

**Comment by bhkim003** [comment]
아 2번 질문은 유의미한 게 맞다는 것을 방금 개선에 성공해서 인지했습니다. 죄송합니다

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 

1. 넵 그렇습니다, 현재 테스트벤치 코드 특성상, gen_repeat_cnt에는 0보다 큰 정수값이 들어가야합니다. gen_repeat_cnt가 0인 경우는 고려 안 하시면 됩니다.
