### ISSUE TITLE
[Data Reorder Unit 내 ]

### ISSUE THREAD

**Issue by joamin7563** [ECE4278/project2#8]

**Comment by joamin7563** [comment]
1. Serializer의 역할이 FIFO내 518bit중 상위 6bit인 offset을 가지고
    512bit를 64bit씩 8개로 끊어서 output으로 나갈 때 나가는 순서를 바꿔주는 역할이라고 이해하였습니다.
    제가 제대로 이해한 것이 맞나요?

2. 1이 맞다면 offset이 6bit라고 교안에 나와있습니다.
    그렇다면 offset의 값은 0~63사이 모든 값을 다 가질 수 있는 것인가요 (혹은 8의 배수만 가능한 것인가요)?

    만약 모든 값이 가능하다면 offset이 2라고 가정하면 [2 ~ 65], [66 ~ 129], ... [450, 451, ... 510, 511, 0, 1] 와 같이 되는 것인가요?
    (괄호 안의 숫자는 "n번째 bit의 값"이라는 의미입니다.)

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

1. 넵 맞습니다. serializer의 역할은 offset을 사용하여 512bit의 데이터를 64bit씩 8개로 끊어서 output으로 나가게 하는 것입니다.
2. offset은 8의 배수만 들어갑니다. Lab11 Term Project ppt의 cache description 슬라이드를 보시면 ARADDR[2:0] = 0이라고 명시되어 있습니다.
만약 모든 값~~ <- 해당 문장에서 offset이 2인 경우는 없지만, 8의 배수라는 조건만 붙인다면 정확히 이해하신것이 맞습니다.

박태원 드림

**Comment by joamin7563** [comment]
네! 늦은 시간에 빠른 답변 감사합니다
