### ISSUE TITLE
CC_TOP 질문

### ISSUE THREAD

**Issue by meenooksun** [ECE4278/project2#9]
CC_TOP의  inct_rid_o, inct_rresp_o, mem_arlen_o.. 등 과 같은 output node들도 알아서 값을 설정해 주어야 하나요??

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다. 

넵 그렇습니다. [#3  ](https://github.com/ECE4278/project2/issues/3)을 참고해주시기 바랍니다.

박태원 드림
